owner: mybigday
repo: service-uptime-beta

# Add your sites here
sites:
  - name: BRICKS BETA
    method: POST
    headers:
      - "X-HEALTHCHECK-SECRET: $X_HEALTHCHECK_SECRET"
    url: https://display-beta.bricks.tools/api/workspace-public-health-check
    assignees:
      - jhen0409
  - name: BRICKS Device BETA
    method: POST
    headers:
      - "X-HEALTHCHECK-SECRET: $X_HEALTHCHECK_SECRET"
    url: https://device-beta.bricks.tools/api/public-health-check
    assignees:
      - jhen0409
  - name: Data Bank BETA
    url: https://bank-beta.bricks.tools/api/not-found
    expectedStatusCodes:
      - 404
    assignees:
      - jhen0409
  - name: Media Flow BETA
    url: https://media-beta.bricks.tools
    expectedStatusCodes:
      - 404
    assignees:
      - jhen0409
  - name: Group (Legacy) BETA
    url: https://group-beta.mybigday.com.tw
    assignees:
      - jhen0409
  - name: Activity Log BETA
    url: https://activity-log-beta.bricks.tools/health
    assignees:
      - hans00

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /service-uptime-beta
  logoUrl: https://cdn.mybigday.com.tw/bricks/bricks.png
  name: BRICKS Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
