owner: mybigday
repo: service-uptime-beta

# Add your sites here
sites:
  - name: BRICKS BETA
    method: HEAD
    url: https://display-beta.bricks.tools
  - name: BRICKS Device BETA
    url: https://device-beta.bricks.tools
    expectedStatusCodes:
      - 404
  - name: BRICKS Bank BETA
    url: https://bank-beta.bricks.tools/api/not-found
    expectedStatusCodes:
      - 404
  - name: MyBigDay Group BETA
    url: https://group-beta.mybigday.com.tw
  - name: BotHub BETA
    url: https://bothub-beta.bricks.tw
  - name: Media Flow BETA
    url: https://media-beta.bricks.tools
    expectedStatusCodes:
      - 404
  - name: Activity Log BETA
    url: https://activity-log-beta.bricks.tools/health

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /service-uptime-beta
  logoUrl: https://cdn.mybigday.com.tw/bricks/bricks.png
  name: BRICKS Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
